export const MOCK_WEEKLY_CONTENT = [
  {
    id: 1,
    experiment_id: "550e8400-e29b-41d4-a716-446655440000",
    language: "en",
    religion: "christianity",
    production_label: true,
    verse_system: "Bible",
    verse_prompt: "Generate an inspiring verse about hope",
    verse_llm_response: "Though the mountains may crumble and the hills may fade, My love for you will never depart, and My covenant of peace shall not be shaken, says the Lord who has compassion on you.",
    explanation_system: "Biblical scholar",
    explanation_prompt: "Explain the meaning of this verse about hope",
    explanation_llm_response: "This verse reminds us that God's love is constant even when everything around us seems unstable. The imagery of mountains crumbling represents how even the most solid things in our lives can change, but God's promises remain. This offers profound hope in difficult times, assuring us that divine compassion continues regardless of our circumstances.",
    explanation_audio_url: "https://storage.googleapis.com/weekly-content/audio/en_hope_explanation.mp3",
    image_url: "https://storage.googleapis.com/weekly-content/images/hope_mountains.jpg",
    image_prompt: "Majestic mountains with sunlight breaking through clouds, symbolizing hope",
    image_aspect_ratio: "16:9",
    image_negative_prompt: "darkness, despair, destruction",
    image_safety_filter_level: "medium",
    inserted_at: "2023-10-15T14:30:00Z",
    updated_at: "2023-10-15T14:30:00Z"
  },
  {
    id: 2,
    experiment_id: "550e8400-e29b-41d4-a716-446655440001",
    language: "en",
    religion: "christianity",
    production_label: true,
    verse_system: "Bible",
    verse_prompt: "Generate a verse about inner peace",
    verse_llm_response: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.",
    explanation_system: "Biblical scholar",
    explanation_prompt: "Explain the meaning of this verse about peace",
    explanation_llm_response: "This verse distinguishes between worldly peace, which is often temporary and circumstantial, and divine peace, which transcends understanding. The peace offered here is not merely the absence of conflict but a profound inner tranquility that remains steadfast despite external circumstances. It encourages believers to reject fear and anxiety, trusting in a higher purpose.",
    explanation_audio_url: "https://storage.googleapis.com/weekly-content/audio/en_peace_explanation.mp3",
    image_url: "https://storage.googleapis.com/weekly-content/images/calm_waters.jpg",
    image_prompt: "Still waters reflecting a sunset with gentle ripples",
    image_aspect_ratio: "16:9",
    image_negative_prompt: "storms, chaos, disturbance",
    image_safety_filter_level: "medium",
    inserted_at: "2023-10-16T10:15:00Z",
    updated_at: "2023-10-16T10:15:00Z"
  },
  {
    id: 3,
    experiment_id: "550e8400-e29b-41d4-a716-446655440002",
    language: "es",
    religion: "christianity",
    production_label: true,
    verse_system: "Biblia",
    verse_prompt: "Generar un verso sobre la fe",
    verse_llm_response: "La fe es la certeza de lo que se espera, la convicción de lo que no se ve. Por ella recibieron aprobación los antiguos.",
    explanation_system: "Erudito bíblico",
    explanation_prompt: "Explicar el significado de este verso sobre la fe",
    explanation_llm_response: "Este verso define la fe como una confianza profunda en lo que esperamos y una seguridad en realidades que no podemos percibir con nuestros sentidos. Nos enseña que la fe no es simplemente un sentimiento, sino una certeza que nos permite actuar con convicción. Los antiguos testigos de la fe fueron aprobados precisamente por esta cualidad, demostrando que la fe auténtica se manifiesta en nuestras acciones y decisiones diarias.",
    explanation_audio_url: "https://storage.googleapis.com/weekly-content/audio/es_fe_explanation.mp3",
    image_url: "https://storage.googleapis.com/weekly-content/images/faith_light.jpg",
    image_prompt: "Rayo de luz atravesando nubes oscuras, simbolizando la fe",
    image_aspect_ratio: "16:9",
    image_negative_prompt: "oscuridad, desesperación, duda",
    image_safety_filter_level: "medium",
    inserted_at: "2023-10-17T09:45:00Z",
    updated_at: "2023-10-17T09:45:00Z"
  },
  {
    id: 4,
    experiment_id: "550e8400-e29b-41d4-a716-446655440003",
    language: "es",
    religion: "christianity",
    production_label: true,
    verse_system: "Biblia",
    verse_prompt: "Generar un verso sobre el amor",
    verse_llm_response: "El amor es paciente, es bondadoso. El amor no es envidioso ni jactancioso ni orgulloso. No se comporta con rudeza, no es egoísta, no se enoja fácilmente, no guarda rencor. El amor no se deleita en la maldad sino que se regocija con la verdad. Todo lo disculpa, todo lo cree, todo lo espera, todo lo soporta.",
    explanation_system: "Erudito bíblico",
    explanation_prompt: "Explicar el significado de este verso sobre el amor",
    explanation_llm_response: "Este pasaje describe el amor verdadero no como un sentimiento pasajero sino como una decisión constante que se manifiesta en acciones concretas. Nos muestra que el amor auténtico se caracteriza por la paciencia y la bondad, mientras rechaza cualidades negativas como la envidia, el orgullo o el egoísmo. El amor descrito aquí es resiliente, optimista y perseverante, capaz de soportar dificultades y mantener la esperanza. Es un ideal al que aspirar en todas nuestras relaciones.",
    explanation_audio_url: "https://storage.googleapis.com/weekly-content/audio/es_amor_explanation.mp3",
    image_url: "https://storage.googleapis.com/weekly-content/images/love_hands.jpg",
    image_prompt: "Manos entrelazadas formando un corazón con luz cálida",
    image_aspect_ratio: "16:9",
    image_negative_prompt: "conflicto, odio, separación",
    image_safety_filter_level: "medium",
    inserted_at: "2023-10-18T11:20:00Z",
    updated_at: "2023-10-18T11:20:00Z"
  }
]; 